    <h2>Mise à jour du produit</h2>
    <form action="" method="post">
        <label for="newProductName">Nouveau nom du produit :</label>
        <input type="text" id="newProductName" name="newProductName" value="<?php echo _escape($product['nomProduits']); ?>" required>
        <br>

        <label for="newProductPrice">Nouveau prix du produit :</label>
        <input type="number" step="0.01" min="0" id="newProductPrice" name="newProductPrice" value="<?php echo _escape($product['prixProduits']); ?>" required>
        <br>

        <label for="newProductDescription">Nouvelle description du produit :</label>
        <textarea id="newProductDescription" name="newProductDescription"><?php echo _escape($product['descriptionProduits']); ?></textarea>
        <br>

        <label for="newProductFamily">Nouvelle famille du produit :</label>
        <input type="text" id="newProductFamily" name="newProductFamily" value="<?php echo _escape($product['familleProduits']); ?>" required>
        <br>

        <label for="newProductGroup">Nouveau groupe du produit :</label>
        <input type="text" id="newProductGroup" name="newProductGroup" value="<?php echo _escape($product['groupeProduits']); ?>" required>
        <br>

        <button type="submit">Mettre à jour</button>
    </form>